name: Update

on:
  schedule:
    - cron: '00 12 14 * *'
  push:
    paths:
      - 'custom.json'
  workflow_dispatch: {}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: 'Clone MAL-Sync'
      uses: actions/checkout@v4
      with:
        repository: MALSync/MALSync
        ref: 'master'
        path: data/MALSync
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Run update
      run: python main.py
    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        add: '*.json'
        message: 'Update'
        default_author: github_actions
        push: true
